[project]
name = "bash-menu-comp"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "rich>=15.0.0",
]

[tool.pyright]
"venvPath" = "."
"venv" = ".venv"
"pythonPlatform" = "Linux"
"typeCheckingMode" = "standard"

[tool.ruff]
line-length = 78
show-fixes = true
unsafe-fixes = true

[tool.ruff.lint]
extend-select = [
  # flake8-bugbear
  "B",
  # flake8-builtins
  "A",
  # flake8-executable
  "EXE",
  # flake4-pie
  "PIE",
  # flake8-symplify
  "SIM",
  # flake8-unused-arguments
  "ARG",
  # isort
  "I",
  # pep8-naming
  "N",
  # pycodestyle
  "E",
  "W",
  # Pyflakes
  "F",
  # pyupgrade
  "UP",
  # Pylint
  "PLE",
]
